### ISSUE TITLE
Helm chart images supports ARM64?

### ISSUE THREAD

**Issue by Miguelixxx** [catalogicsoftware/cloudcasa-helmchart#7]
I have deployed the chart helm in a k3s cluster on arm64 and I get errors /usr/local/bin/kubeagentmanager: exec format error

**Comment by bobadair** [comment]
Hi @Miguelixxx. We don't currently have a build of the agent for arm64 architecture, but support for it is on our roadmap. If you have a need for arm64 support, please contact support@cloudcasa.io. We'd be happy to discuss your requirements.

**Comment by bobadair** [comment]
We added full arm64 support to the CloudCasa agent last October, and PR #9 will add it to the Helm chart as well.

**Comment by bobadair** [comment]
Resolved by #19
